# Template for Streamlit secrets configuration
# Copy this file to .streamlit/secrets.toml and add your actual API keys

[api_keys]
GROQ_API_KEY = "your_groq_api_key_here"
CLOUDFLARE_API_KEY = "your_cloudflare_api_key_here"
CLOUDFLARE_ACCOUNT_ID = "your_account_id_here"

# Instructions:
# 1. Get your Groq API key from: https://console.groq.com/
# 2. Get your Cloudflare API key and Account ID from: https://dash.cloudflare.com/
# 3. Replace the placeholder values above with your actual keys
# 4. Save this file as .streamlit/secrets.toml (note the dot prefix)
# 5. The .gitignore file will ensure your secrets are not committed to version control
